[2023-05-11T10:57:09.951+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T10:55:12.119192+00:00/task_id=name_filepath_task permission to 509
[2023-05-11T10:57:10.091+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T10:55:12.119192+00:00/task_id=name_filepath_task permission to 509
[2023-05-11T10:57:10.235+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_processing.name_filepath_task manual__2023-05-11T10:55:12.119192+00:00 [queued]>
[2023-05-11T10:57:10.288+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_processing.name_filepath_task manual__2023-05-11T10:55:12.119192+00:00 [queued]>
[2023-05-11T10:57:10.293+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-11T10:57:10.423+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): name_filepath_task> on 2023-05-11 10:55:12.119192+00:00
[2023-05-11T10:57:10.446+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tiktok_processing', 'name_filepath_task', 'manual__2023-05-11T10:55:12.119192+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/task_7_1.py', '--cfg-path', '/tmp/tmpanhvv561']
[2023-05-11T10:57:10.440+0000] {standard_task_runner.py:57} INFO - Started process 1104 to run task
[2023-05-11T10:57:10.457+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask name_filepath_task
[2023-05-11T10:57:10.666+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-05-11T10:57:10.793+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=tiktok_processing/run_id=manual__2023-05-11T10:55:12.119192+00:00/task_id=name_filepath_task permission to 509
[2023-05-11T10:57:10.796+0000] {task_command.py:410} INFO - Running <TaskInstance: tiktok_processing.name_filepath_task manual__2023-05-11T10:55:12.119192+00:00 [running]> on host 49e2673af856
[2023-05-11T10:57:11.030+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_processing' AIRFLOW_CTX_TASK_ID='name_filepath_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T10:55:12.119192+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-11T10:55:12.119192+00:00'
[2023-05-11T10:57:11.032+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: name_filepath() missing 1 required positional argument: 'sensor_response'
[2023-05-11T10:57:11.043+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=tiktok_processing, task_id=name_filepath_task, execution_date=20230511T105512, start_date=20230511T105710, end_date=20230511T105711
[2023-05-11T10:57:11.082+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task name_filepath_task (name_filepath() missing 1 required positional argument: 'sensor_response'; 1104)
[2023-05-11T10:57:11.119+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T10:57:11.175+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
